### ISSUE TITLE
No module named lxml

### ISSUE THREAD

**Issue by dauge** [Siltaar/drop_alternatives#1]
Got this error 
lrv: python2 -SE /opt/drop_alternatives/drop_alternatives.py: Traceback (most recent call last):
lrv: python2 -SE /opt/drop_alternatives/drop_alternatives.py:   File "/opt/drop_alternatives/drop_alternatives.py", line 11, in <module>
lrv: python2 -SE /opt/drop_alternatives/drop_alternatives.py:     from lxml import html
lrv: python2 -SE /opt/drop_alternatives/drop_alternatives.py: ImportError: No module named lxml
lrv: python2 -SE /opt/drop_alternatives/drop_alternatives.py: command returned 1

missing dependency ?

**Comment by Siltaar** [comment]
Hello,

As explain in the commit log, and README, drop_alternatives is now a **python3** program (and needs lxml and cssselect to work on machine where `python3-lxml` and `python3-cssselect` are not already installed).
